# permissions for end users to edit prestoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: presto-editor-role
rules:
- apiGroups:
  - skittles.quercy.co
  resources:
  - prestoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - skittles.quercy.co
  resources:
  - prestoes/status
  verbs:
  - get
