# permissions for end users to view prestoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: presto-viewer-role
rules:
- apiGroups:
  - skittles.quercy.co
  resources:
  - prestoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - skittles.quercy.co
  resources:
  - prestoes/status
  verbs:
  - get
