
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: manager-role
  namespace: multicloud-k8s-demo-operator-system
rules:
- apiGroups:
  - skittles.quercy.co
  resources:
  - demoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - skittles.quercy.co
  resources:
  - demoes/status
  verbs:
  - get
  - patch
  - update
